Issue/fatal error requests
wagtail/wagtail-wordpress-import pull request #125
Opened 2021-12-17 15:56 UTC by nickmoreton

# Import stops with error when fetching images

The block_builder_defaults.py has been refactored including adjustments to fetch_url() 

---

- Testing
    - [ ] CI passes
    - [ ] If necessary, tests are added for new or fixed behaviour
    - [ ] These changes do not reduce test coverage
- Documentation.
    - [ ] Documentation changes are not necessary because: no user changes have been made

2021-12-24 12:13 UTC, Morsey187 requested changes
This works great, I've only got a few comments

2021-12-24 12:13 UTC, Morsey187 commented on wagtail_wordpress_import/block_builder_defaults.py
> +                "WAGTAIL_WORDPRESS_IMPORTER_REQUESTS_SETTINGS",
**Question**: Is `WAGTAIL_WORDPRESS_IMPORTER_REQUESTS_SETTINGS` referenced anywhere? if not it would be nice to have an example in the docs or in the setup [instructions](https://github.com/torchbox/wagtail-wordpress-import#initial-app-and-package-setup)

2021-12-24 12:13 UTC, Morsey187 commented on wagtail_wordpress_import/block_builder_defaults.py
> +    except requests.ConnectionError:
**Suggestion**: 

I believe RequestException is the base class exception so if you want to keep it specific then it might be better to put this one last https://stackoverflow.com/a/47007419


I've added some snippets below which could work to shorten the code a little but I haven't got a lot of experience with exepction handling so not sure if they would be considered bad practise or not:
```python
    except (requests.ConnectionError, requests.HTTPError, requests.ReadTimeout, requests.Timeout, requests.ConnectTimeout, requests.RequestException) as e :
        print(f"{type(e).__name__}: {src}")
        return None, False, None
```
or
```python
    except Exception as e:
        print(f"{type(e).__name__}: {src}")
        return None, False, None
```

2021-12-24 12:13 UTC, Morsey187 commented on wagtail_wordpress_import/block_builder_defaults.py
> +                "WAGTAIL_WORDPRESS_IMPORTER_VALID_IMAGE_CONTENT_TYPES",
**Suggestion**: Same as `WAGTAIL_WORDPRESS_IMPORTER_REQUESTS_SETTINGS` it might be nice to add this to the docs, perhaps with examples of their default values

2021-12-24 12:13 UTC, Morsey187 commented on wagtail_wordpress_import/block_builder_defaults.py
> +                    "",
I think this ones missing an attribute name.

2022-01-03 09:33 UTC, fabienheureux commented
@nickmoreton I just tried using this PR as I need it for my current project. 
From a functionnal point of view, it works as expected :+1:

2022-01-03 15:13 UTC, nickmoreton commented on wagtail_wordpress_import/block_builder_defaults.py
> +                "WAGTAIL_WORDPRESS_IMPORTER_REQUESTS_SETTINGS",
I'm adding a new issue for this to update the docs later on. Thanks

2022-01-03 15:15 UTC, nickmoreton commented on wagtail_wordpress_import/block_builder_defaults.py
> +                "WAGTAIL_WORDPRESS_IMPORTER_REQUESTS_SETTINGS",
#133

2022-01-03 15:15 UTC, nickmoreton commented on wagtail_wordpress_import/block_builder_defaults.py
> +    except requests.ConnectionError:
#134

2022-01-03 15:18 UTC, nickmoreton commented on wagtail_wordpress_import/block_builder_defaults.py
> +                "WAGTAIL_WORDPRESS_IMPORTER_VALID_IMAGE_CONTENT_TYPES",
#133

2022-01-03 15:18 UTC, nickmoreton commented on wagtail_wordpress_import/block_builder_defaults.py
> +                    "",
#133

2022-01-03 15:20 UTC, nickmoreton commented
> @nickmoreton I just tried using this PR as I need it for my current project.
> From a functionnal point of view, it works as expected 👍

Thanks @fabienheureux I have opened a couple of issues for the outstanding comments. As you have tested it locally I'll merge this in now.

2022-01-03 15:20 UTC, merged