#13 pre-filter documentation
wagtail/wagtail-wordpress-import pull request #36
Opened 2021-10-06 16:38 UTC by nickmoreton

2021-10-11 18:19 UTC, kaedroho requested changes

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +An package to extend Wagatil CMS and import wordpress content types from an xml file into a Wagail project.
How about:

An extension for Wagtail CMS that imports WordPress content from an exported XML file into Wagtail models

What do you think?

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +Create page models, image models, document models and more.
I'm not sure if we need this

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +Place your xml files somewhere in your project. The file can have any name you choose.
I think this can import any file on disk so is it necessary to move the files into the project folder?

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +The configuration is set to import all items in the xml file that have a `<wp:post_type>` = `post` or `page`. Also the command only imports an item that has `<wp:status>` = `draft` or `publish`. By d
xml => XML
By default => By default,

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +- It's default behavior is to remove all comments and comment data.
It's => Its
Behaviour was already correct spelling

2021-10-11 18:19 UTC, kaedroho commented on README.md
> +This command will output a json file inside the json folder at the root of your project. The output can help you decide which fields should be included in your import as well as providing a nice shor
json => JSON
xml => XML

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +Each time the import processes the body content of a page a series of filters are run on the content to transform it.
How about:

Each time the importer processes a page, the body content is transformed by a series of filters

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +# Why use pre-filters
I think first sentence of this section should answer the question and subsequent sentences provide more detail/examples?

For example:

```
Pre-filters allow transformations to be made on a page's body content before it is converted into blocks. This allows any behaviour that affects how the blocks will be generated to be implemented.

For example, WordPress interprets lines of text separated by two line breaks as separate paragraphs so there's a pre-filter that converts them into separate ``<p>`` tags so that the block generator will convert them into separate paragraph blocks.
```

What do you think?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +This filter implements the same process as `wpauto` to convert the raw html content into html content  with tags around every piece of content. It avoids changing anything that is acceptable. In the
`wpauto` => `wpautop`
html => HTML

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +1. linebreaks_wp_filter.py: this is a [python implementation](https://gist.github.com/albertsun/1160201/0a1f7d7a509fbcfa580725ed3783a29af51b62b4) of the wordpress function wpauto
If we're referencing the py files, should we link to the code? Otherwise, maybe we should use the module paths instead?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +2. normalize_styles_filter.py: using [BeautifulSoup](https://www.crummy.com/software/)
Not sure if it's relevant to write how it was implemented here

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +This filter converts inline style attributes to a format we can work with in the next filter because the format of style attributes can be different in some for each tag. It deals with word-case, spa
Wondering if there's any reason this is a separate filter?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +- `font-weigh:bold;` is better represented using a `<b>` tag
`font-weigh:bold;` => `font-weight: bold;`

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +- `float: left;` is better represented by a class of `left-align`
I think rather than saying "is better represented by", could we word this as "is converted into"?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +This filter is run last and removes tags based on a range of `ALLOWED` Tags, Attributes and Styles.
Wondering why allowed is capitalised here? Is this a setting? If so, please could you add an example?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +The order the pre-filters are run will have an impact on the final html output. The default order is:
html => HTML

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +    1. filter_linebreaks_wp()
This is already documented here: https://github.com/torchbox/wagtail-wordpress-import/pull/36/files#diff-16d24c203df2c01d2eab0a40ebf8a1f3e693e4a6cb03e79699664b8366a30150R38

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +DEFAULT_PREFILTERS = [
I think ``DEFAULT_PREFILTERS`` is an implementation detail. We probably should write this something like:


By default, ``WAGTAIL_WORDPRESS_IMPORT_PREFILTERS`` is set to the following:

```
WAGTAIL_WORDPRESS_IMPORT_PREFILTERS = [
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.linebreaks_wp_filter.filter_linebreaks_wp",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.normalize_styles_filter.filter_normalize_style_attrs",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.fix_styles_filter.filter_fix_styles",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.bleach_filter.filter_bleach_clean",
    },
]
```

This way it's in a state where someone could copy it out of the docs and tweak it

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +copy the `DEFAULT_PREFILTERS` above to your own settings file and change the name to
As above, I think we should change the example to not even mention ``DEFAULT_PREFILTERS`` since this looks like an implementation detail to me

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +    most likely a string but depending on your implementation
Do we allow pre-filters to be used on other types?

2021-10-11 18:19 UTC, kaedroho commented on docs/prefilters.md
> +    you probably won't need to pass in any options
Could you describe what it's for?

2021-10-11 18:22 UTC, kaedroho commented on docs/prefilters.md
> +DEFAULT_PREFILTERS = [
I think these module paths are a bit long, would it be possible to re-export them from ``wagtail_wordpress_import.prefilters`` to make them shorter and more memorable? For example:

```
WAGTAIL_WORDPRESS_IMPORT_PREFILTERS = [
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.linebreaks_wp",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.normalize_style_attrs",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.fix_styles",
    },
    {
        "FUNCTION": "wagtail_wordpress_import.prefilters.bleach_clean",
    },
]
```

Also, think we could pick a better name for ``fix_styles``. How about ``styles_to_tags``?

2021-10-12 11:57 UTC, nickmoreton commented on docs/prefilters.md
> +This filter converts inline style attributes to a format we can work with in the next filter because the format of style attributes can be different in some for each tag. It deals with word-case, spa
I can only think I did it that way so it could be set as not used in the config. Off the top of my head Im sure it could be part of fix_styles though and runs there.

2021-10-12 11:59 UTC, nickmoreton commented on docs/prefilters.md
> +- `font-weigh:bold;` is better represented using a `<b>` tag
I have added the space here. But just to note the normalize_styles_filter.py does actually exclude the space when it does it's thing at the moment when it adds the style string back in.

2021-10-12 12:01 UTC, nickmoreton commented on docs/prefilters.md
> +- `float: left;` is better represented by a class of `left-align`
I'll change this but realise there's inconsistency around the style spacing above, float: left should have read float:left but i'll leave it as is for now.

2021-10-12 12:05 UTC, nickmoreton commented on docs/prefilters.md
> +This filter is run last and removes tags based on a range of `ALLOWED` Tags, Attributes and Styles.
I added a link and adjusted the references so they look like settings.

2021-10-12 12:07 UTC, nickmoreton commented on docs/prefilters.md
> +    1. filter_linebreaks_wp()
I have removed this duplicate list

2021-10-12 12:10 UTC, nickmoreton commented on docs/prefilters.md
> +DEFAULT_PREFILTERS = [
I'll create an issue for this: https://github.com/torchbox/wagtail-wordpress-import/issues/39

2021-10-12 12:13 UTC, nickmoreton commented on docs/prefilters.md
> +copy the `DEFAULT_PREFILTERS` above to your own settings file and change the name to
I have altered this now

2021-10-12 12:16 UTC, nickmoreton commented on docs/prefilters.md
> +    most likely a string but depending on your implementation
I have changed this

2021-10-12 12:16 UTC, nickmoreton commented on docs/prefilters.md
> +    you probably won't need to pass in any options
I have added an example

2021-10-12 12:17 UTC, nickmoreton commented on README.md
> +This command will output a json file inside the json folder at the root of your project. The output can help you decide which fields should be included in your import as well as providing a nice shor
I changed the spellings

2021-10-12 12:18 UTC, nickmoreton commented on docs/prefilters.md
> +Each time the import processes the body content of a page a series of filters are run on the content to transform it.
i changed this

2021-10-12 12:18 UTC, nickmoreton commented on docs/prefilters.md
> +# Why use pre-filters
Cool i changed this

2021-10-12 12:19 UTC, nickmoreton commented on docs/prefilters.md
> +This filter implements the same process as `wpauto` to convert the raw html content into html content  with tags around every piece of content. It avoids changing anything that is acceptable. In the
I changed the spellings

2021-10-12 12:20 UTC, nickmoreton commented on docs/prefilters.md
> +1. linebreaks_wp_filter.py: this is a [python implementation](https://gist.github.com/albertsun/1160201/0a1f7d7a509fbcfa580725ed3783a29af51b62b4) of the wordpress function wpauto
I removed the links which I think removes too much information at that point. We have references to the files below anyway.

2021-10-12 12:21 UTC, nickmoreton commented on docs/prefilters.md
> +2. normalize_styles_filter.py: using [BeautifulSoup](https://www.crummy.com/software/)
OK ta. I removed the extra text

2021-10-12 12:22 UTC, nickmoreton commented on README.md
> +An package to extend Wagatil CMS and import wordpress content types from an xml file into a Wagail project.
Like it

2021-10-12 12:22 UTC, nickmoreton commented on README.md
> +Create page models, image models, document models and more.
I removed this

2021-10-12 12:24 UTC, nickmoreton commented on README.md
> +Place your xml files somewhere in your project. The file can have any name you choose.
I changed this

2021-10-12 12:25 UTC, nickmoreton commented on README.md
> +The configuration is set to import all items in the xml file that have a `<wp:post_type>` = `post` or `page`. Also the command only imports an item that has `<wp:status>` = `draft` or `publish`. By d
I changed the spellings

2021-10-12 12:27 UTC, nickmoreton commented on README.md
> +- It's default behavior is to remove all comments and comment data.
I changed the spellings here

2021-10-14 09:58 UTC, nickmoreton commented
@kaedroho Just checking here if it's OK to merge this one in too? I did make changes to it.

2021-10-18 16:10 UTC, nickmoreton commented
These docs are now out of date following: https://github.com/torchbox/wagtail-wordpress-import/pull/48 but I have added them to the docs ticket: https://projects.torchbox.com/projects/wordpress-to-wagtail-importer-package/tickets/55

2021-10-18 16:19 UTC, nimasmi commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
**Suggestion**: add a mention of where and how to create a PostPage instance, e.g.

```python
from wagtail_wordpress_import.models import WPImportedPageMixin

class PostPage(WPImportedPageMixin, Page):
    pass
```

2021-10-18 16:19 UTC, nimasmi commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
**Question**: I see the default in the management command. Does the user need to specify an import path for this when running that command?

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +Pre-filters allow transformations to be made on a page's body content before it is converted into blocks. This allows any behavior that affects how the blocks will be generated to be implemented.
**Suggestion**: clarify sentence.

```suggestion
Pre-filters allow transformations to be made on a page's body content before it is converted into blocks. This allows you to implement behaviour that affects how the blocks will be generated.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +The content could also include shortcodes which wordpress uses to represent more structured HTML that might include nested HTML tags like in a FORM. There's a filter that will convert it to a block t
**Suggestion**: consistency

```suggestion
The content could also include shortcodes which WordPress uses to represent more structured HTML that might include nested HTML tags like in a FORM. There's a filter that will convert it to a block type/string that can be used to build the block type in the block builder.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +The content could also include shortcodes which wordpress uses to represent more structured HTML that might include nested HTML tags like in a FORM. There's a filter that will convert it to a block t
**Question**: 

> There's a filter that will convert it to a block type/string that can be used to build the block type in the block builder.

Is there? I don't understand this sentence.

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +**The above filters run, by default, in the order above before the content is passed into the page model or parsed to stream field blocks.**
**Suggestion**: consistency

```suggestion
**The above filters run, by default, in the order above before the content is passed into the page model or parsed to StreamField blocks.**
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +The output of the last pre-filter is used to build the stream field blocks in a later process.
```suggestion
The output of the last pre-filter is used to build the StreamField blocks in a later process.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +You can use the package without providing any configuration for pre-filters. We provide a small number of useful pre-filters that process html content before it's used to build out the stream field b
```suggestion
You can use the package without providing any configuration for pre-filters. We provide a small number of useful pre-filters that process html content before it's used to build out the StreamField blocks.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +Wordpress uses line breaks as a mechanism for vertical spacing of rendered HTML (paragraphs).
```suggestion
WordPress uses line breaks as a mechanism for vertical spacing of rendered HTML (paragraphs).
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +This filter converts inline style attributes to a format we can work with in the next filter because the format of style attributes can be different in some for each tag. It deals with word-case, spa
**Issue**: This situation is changed in #48, making this and `filter_fix_styles` documentation out of date.

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +This filter applies any inline style to the html tag that is useful in the context of the Wagtail rich text editor. It performs wrapping a tag around a piece of text as well ass applying classes to a
```suggestion
This filter applies any inline style to the html tag that is useful in the context of the Wagtail rich text editor. It performs wrapping a tag around a piece of text as well as applying classes to a tag to represent alignment.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +- `font-weigh: bold;` is converted to a `<b>` tag
```suggestion
- `font-weight: bold;` is converted to a `<b>` tag
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +DEFAULT_PREFILTERS = [
**Issue**: there's a discrepancy between `WAGTAIL_WORDPRESS_IMPORT_PREFILTERS` in the preceding paragraph, and the variable name of this settings dict.

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +]
**Question**: Are we changing the path names here in this MR, or is that done elsewhere, e.g. in #39?

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +Create you own settings config called `WAGTAIL_WORDPRESS_IMPORT_PREFILTERS` with the FUNCTIONS you need to run, in the order they should be run.
```suggestion
Create your own settings config called `WAGTAIL_WORDPRESS_IMPORT_PREFILTERS` with the FUNCTIONS you need to run, in the order they should be run.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +`my-custom-tag` would be appended to the `ALLOWED_TAGS` in the bleach_filters
**Question**: What are "the bleach_filters"? Is this a typo? I see no explicit mention of it in the repo.

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +    "FUNCTION": "[app].[file].[method]",
**Suggestion**: Just call it "path to function". We don't want to dictate where users put this method, nor need to tell them how to write Python.

```suggestion
    "FUNCTION": "[path to function]",
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +at the position to match the running order you need. `[app].[file].[method]` is the  dotted path to your function.
**Suggestion**: ditto.

```suggestion
at the position to match the running order you need. `[path to function]` is the  dotted path to your function.
```

2021-10-18 16:19 UTC, nimasmi commented on docs/prefilters.md
> +If you use the provided `WPImportedPageMixin` it has fields to receive the output from each pre-filter step which can be see on the Debug tab when editing a page. [Read about the mixin](models.md)
```suggestion
If you use the provided `WPImportedPageMixin` it has fields to receive the output from each pre-filter step which can be seen on the Debug tab when editing a page. [Read about the mixin](models.md)
```

2021-10-18 16:19 UTC, nimasmi commented on README.md
>  # Inital setup
```suggestion
# Initial setup
```

2021-10-18 17:01 UTC, nickmoreton commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
Ah... this is the main readme which is not yet complete. We aren't doing that here, it's just for the prefilters.md

2021-10-18 17:03 UTC, nickmoreton commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
This also isn't been worked on here. Sorry

2021-10-18 17:31 UTC, nickmoreton commented on docs/prefilters.md
> +]
Yes elsewhere, specifically In the new codebase ticket

2021-10-18 18:05 UTC, nickmoreton commented on docs/prefilters.md
> +`my-custom-tag` would be appended to the `ALLOWED_TAGS` in the bleach_filters
I can clear this up later and added an issue for it #50

2021-10-19 08:53 UTC, nickmoreton commented on docs/prefilters.md
> +The content could also include shortcodes which wordpress uses to represent more structured HTML that might include nested HTML tags like in a FORM. There's a filter that will convert it to a block t
I created an issue #52 to remove this paragraph for now

2021-10-19 09:00 UTC, nickmoreton commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
#54 Issue created

2021-10-19 09:01 UTC, nickmoreton commented on README.md
> +The configuration is set to import all items in the XML file that have a `<wp:post_type>` = `post` or `page`. The command only imports an item that has `<wp:status>` = `draft` or `publish`. By defaul
#54 Issue created

2021-10-19 09:32 UTC, nickmoreton commented on docs/prefilters.md
> +The content could also include shortcodes which wordpress uses to represent more structured HTML that might include nested HTML tags like in a FORM. There's a filter that will convert it to a block t
I've been thinking ahead here, you are right there isn't any shortcode handling in place yet.

2021-10-19 09:53 UTC, merged